name: Docker Image Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag homosanians/disgracediscordbot:$(date +%s)
    - name: Push to the registry
      run: docker push homosanians/disgracediscordbot:$(date +%s)
