name: Docker Image Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get commit metadata
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)" && echo "::set-output name=branch::$(echo ${GITHUB_REF} | cut -c12-999)"
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: homosanians/otherworldbot
        build_args: GIT_COMMIT=${{steps.slug.outputs.sha8}},GIT_BRANCH=${{steps.slug.outputs.branch}}
        tags: ${{steps.slug.outputs.branch}}
