name: Docker Image Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    env:
      SHA8: ${GITHUB_SHA::8}
      BRANCH: ${GITHUB_REF:11}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: homosanians/otherworldbot
        build_args: GIT_COMMIT=${{ENV.SHA8}},GIT_BRANCH=${{ENV.BRANCH}}
        tags: latest
